#synthetic data 
1. Creation and Read
2. Adding noise
3. Augmentation
4. Validation
5. Cleaning
6. Visulization
7. Modeling
8. Evaluation


Modeling is the process of converting a real time problem into a mathematical function that can learn patterns from data and predictions on unseen data.
Modeling Pipeline
1. Problem Definition
    Goal: Predict whether a student will drop[1] or continue[0]
    Type: Supervised learning --> Binary Classification
2. Feature Selection
   Features:
   1. Attendance
   2. Average Marks
   3. Assignments Submitted
   4. Disciplinary cases
3. Test-Train Split
    80%--Traning
    20%--Testing
4. Algorithm Selection
    No algorithm performs best in all scenarious/for all problems
    Model Comparisons
    1. Accuracy
    2. Recall
    3. Interoperability
    4. Stability
5. Model Training
6. Evaluation and Comparison
    Use Multiple Metics
    1. Confusion 
        Actual/Predicted            No Dropout[0]           Dropout[1]
        No Dropout[0]                     TN                      FP
        Dropout[1]                        FN                      TP
    
                  
    2. Core Evaluation Matrices
        2.1 Accuracy        TP+TN/TP+TN+FP+FN   Overall Correctness
        2.2 Precision       TP/TP+FP            How reliable dropout predictions
        2.3 Recall          TP/TF+FN            How mqny actual deopouts we catchec
        2.4 F1-Score        2*Precision* Recall/Precision+Recall. it is balance betwenn Precision and Recall
        2.5 ROC-AUC         it is a curve



7. Final Model Selection

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC




In [2]:
from sklearn.metrics import(confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score)

In [5]:
np.random.seed(42)
n=500

In [8]:
data = pd.DataFrame({
    "attendance_rate":np.random.normal(75,10,n).clip(40,100),
    "avg_marks":np.random.normal(80,40,n).clip(30,100),
    "assignments_submitted":np.random.normal(80,15,n).clip(20,100),
    "disciplinary_cases":np.random.poisson(1.2,n)
})

In [9]:
data["dropout"] =(
    (data["attendance_rate"]<60) |
    (data["avg_marks"]<50) |
    (data["disciplinary_cases"]>3)
).astype(int)

In [10]:
data

attendance_rate   avg_marks  ...  disciplinary_cases  dropout
0          70.356797   95.698606  ...                   1        0
1          71.539156  100.000000  ...                   1        0
2          82.284699  100.000000  ...                   1        0
3          73.256250  100.000000  ...                   3        0
4          71.809923  100.000000  ...                   1        0
..               ...         ...  ...                 ...      ...
495        78.274198  100.000000  ...                   3        0
496        53.352857   65.529604  ...                   2        1
497        88.386217  100.000000  ...                   0        0
498        66.688301   66.963547  ...                   0        0
499        89.170438   79.580601  ...                   1        0

[500 rows x 5 columns]

In [11]:
X = data.drop("dropout", axis=1)

In [14]:
print(X)

     attendance_rate   avg_marks  assignments_submitted  disciplinary_cases
0          70.356797   95.698606             100.000000                   1
1          71.539156  100.000000              63.896971                   1
2          82.284699  100.000000              59.927614                   1
3          73.256250  100.000000              78.692020                   3
4          71.809923  100.000000              89.954840                   1
..               ...         ...                    ...                 ...
495        78.274198  100.000000              91.292408                   3
496        53.352857   65.529604              74.048825                   2
497        88.386217  100.000000              76.013365                   0
498        66.688301   66.963547              80.042158                   0
499        89.170438   79.580601             100.000000                   1

[500 rows x 4 columns]


In [15]:
y = data["dropout"]

In [17]:
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
495    0
496    1
497    0
498    0
499    0
Name: dropout, Length: 500, dtype: int64


In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [19]:
print(X_train)

     attendance_rate   avg_marks  assignments_submitted  disciplinary_cases
227        76.211180   68.248134              64.413897                   0
417        78.361600  100.000000              85.664218                   4
203        72.284755  100.000000              64.953320                   0
126        77.436325   96.306250              78.185573                   1
329        56.943945   40.897515              70.149728                   0
..               ...         ...                    ...                 ...
106        65.774873   49.532472              80.526900                   5
270        79.516327   71.794071             100.000000                   1
348        64.514759   90.435563             100.000000                   0
435        61.171330   30.000000              82.959895                   0
102        78.401177   92.064770              75.561224                   0

[375 rows x 4 columns]


In [20]:
print(X_test)

     attendance_rate   avg_marks  assignments_submitted  disciplinary_cases
361        75.756723  100.000000              65.196120                   3
73         59.838642   42.423769              60.704988                   1
374        82.420830   30.000000              90.906200                   0
155        69.207448   30.000000              94.535351                   5
104        64.422844   30.000000              64.523981                   1
..               ...         ...                    ...                 ...
220        97.964431   30.000000              65.054875                   1
176        75.858404   84.500628              76.189157                   1
320        70.252264  100.000000              96.915680                   0
153        63.613321   63.098356              82.017093                   1
231        60.588674   37.627495              74.103182                   0

[125 rows x 4 columns]


In [21]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [22]:
print(X_train_scaled)

[[ 0.06718503 -0.34358692 -1.09493979 -1.05123492]
 [ 0.27715779  0.95297452  0.40890261  2.59888634]
 [-0.3162015   0.95297452 -1.05676589 -1.05123492]
 ...
 [-1.07488456  0.56241856  1.42341705 -1.05123492]
 [-1.4013458  -1.90541814  0.21752317 -1.05123492]
 [ 0.28102215  0.6289459  -0.30606591 -1.05123492]]


In [23]:
models = {
    "Logistic Regression":LogisticRegression(max_iter=1000),
    "Decision Tree":DecisionTreeClassifier(max_depth=5),
    "Random Forest":RandomForestClassifier(n_estimators=100),
    "SVM":SVC(probability=True)
}

In [24]:
result=[]

for name, model in models.items():
    if name in["Logistic Regression","SVM"]:
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
        y_prob = model.predict_proba(X_test_scaled)[:1]
    else:
        model.fit(X_train,y_train)
        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:1]

In [25]:
cm =  confusion_matrix(y_test,y_pred)

In [26]:
result.append({
    "Model": name,
    "Accuracy":accuracy_score(y_test,y_pred),
    "Precision":precision_score(y_test,y_pred),
    "Recall":recall_score(y_test,y_pred),
    "FI-Score":f1_score(y_test,y_pred),
    "ROC-AUC":roc_auc_score(y_test,y_pred),
    "Confusion Matrix":cm
})

In [27]:
result_df = pd.DataFrame(result)
print(result_df)

  Model  Accuracy  Precision    Recall  FI-Score   ROC-AUC    Confusion Matrix
0   SVM     0.968   0.909091  0.967742    0.9375  0.967914  [[91, 3], [1, 30]]


In [28]:
for r in result:
    print(f"\n{r['Model']}Confusion Matrix:")
    print(r["Confusion Matrix"])


SVMConfusion Matrix:
[[91  3]
 [ 1 30]]
