#synthetic data creation

In [11]:
import pandas as pd 

##synthetic data creation

In [12]:

#create a simple,clean syntehtic dataset
data={

    "student_id": [101,102,103,104],
    "name":["sourabh","anjali","abhishek","deepanshu"],
    "age":[40,35,26,23],
    "marks":[90,85,80,75],
    "department":["AIML","AR","CSE","ME"]


}

df=pd.DataFrame(data)

In [13]:
df

student_id       name  age  marks department
0         101    sourabh   40     90       AIML
1         102     anjali   35     85         AR
2         103   abhishek   26     80        CSE
3         104  deepanshu   23     75         ME

In [16]:
#create a simple,unclean syntehtic dataset
data={

    "student_id": [101,102,103,104,None],
    "name":["sourabh","anjali",None,"abhishek","deepanshu"],
    "age":[40,None,35,26,23],
    "marks":[90,85,None,80,75],
    "department":["AIML","AR","CSE",None,"ME"]


}

df=pd.DataFrame(data)

In [17]:
df

student_id       name   age  marks department
0       101.0    sourabh  40.0   90.0       AIML
1       102.0     anjali   NaN   85.0         AR
2       103.0       None  35.0    NaN        CSE
3       104.0   abhishek  26.0   80.0       None
4         NaN  deepanshu  23.0   75.0         ME

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   student_id  4 non-null      float64
 1   name        4 non-null      object 
 2   age         4 non-null      float64
 3   marks       4 non-null      float64
 4   department  4 non-null      object 
dtypes: float64(3), object(2)
memory usage: 328.0+ bytes


In [19]:
import pandas as pd
import numpy as np


In [22]:
np.random.seed(42)
#n-10
print(np.random.randint(1,100,10))

[52 93 15 72 61 21 83 87 75 75]


In [ ]:
#fix random number on a particular seed
np.random.seed(24)
#n-10
print(np.random.randint(1,100,10))

[35  4 65 88 18 18  2 80  5 83]


In [ ]:
#not fix random number when seed is not defined
#np.random.seed(24)
#n-10
print(np.random.randint(1,100,10))

[47 66 48 90 75 36 65 28 98 34]


In [86]:
import pandas as pd
np.random.seed(41)
n=1000

df=pd.DataFrame ({

    "student_id": np.arange(101,101+n),
    
    "age":np.random.randint(18,24,size=n),
    "marks":np.random.randint(40,100,size=n),
    "department":np.random.choice(["AIML","AR","CSE","ME","automation"],size=n)


})

df=pd.DataFrame(df)
df

student_id  age  marks department
0           101   18     92       AIML
1           102   21     56        CSE
2           103   22     65        CSE
3           104   20     46       AIML
4           105   18     80       AIML
..          ...  ...    ...        ...
995        1096   21     48       AIML
996        1097   21     76        CSE
997        1098   20     42       AIML
998        1099   21     62         AR
999        1100   23     54         ME

[1000 rows x 4 columns]

In [103]:
from numpy.random.mtrand import sample
# Introduce Missing values in Age, Marks and Department
for col in ["Age","Marks","department"]:
    df.loc[df.sample(frac=0.05).index,col]=np.nan

In [96]:
#duplicate records/rows
pd.concat([df,df.sample(20)],ignore_index=True)

#introduce invalid ages
df.loc[df.sample(10).index,"Age"]=np.random.choice([-5,240],size=10)

In [97]:
#introduce outliners
df.loc[df.sample(10).index,"Marks"]=np.random.choice([150,240],size=10)

In [105]:

df

student_id  age  marks department  Age  Marks  Department
0           101   18     92       AIML  NaN    NaN         NaN
1           102   21     56        CSE  NaN    NaN         NaN
2           103   22     65        CSE  NaN    NaN         NaN
3           104   20     46       AIML  NaN    NaN         NaN
4           105   18     80       AIML  NaN    NaN         NaN
..          ...  ...    ...        ...  ...    ...         ...
995        1096   21     48       AIML  NaN    NaN         NaN
996        1097   21     76        CSE  NaN    NaN         NaN
997        1098   20     42       AIML  NaN    NaN         NaN
998        1099   21     62         ar  NaN    NaN         NaN
999        1100   23     54         me  NaN    NaN         NaN

[1000 rows x 7 columns]

In [106]:
df

student_id  age  marks department  Age  Marks  Department
0           101   18     92       AIML  NaN    NaN         NaN
1           102   21     56        CSE  NaN    NaN         NaN
2           103   22     65        CSE  NaN    NaN         NaN
3           104   20     46       AIML  NaN    NaN         NaN
4           105   18     80       AIML  NaN    NaN         NaN
..          ...  ...    ...        ...  ...    ...         ...
995        1096   21     48       AIML  NaN    NaN         NaN
996        1097   21     76        CSE  NaN    NaN         NaN
997        1098   20     42       AIML  NaN    NaN         NaN
998        1099   21     62         ar  NaN    NaN         NaN
999        1100   23     54         me  NaN    NaN         NaN

[1000 rows x 7 columns]

In [107]:
#inconsistent text formatting
df["department"]=df["department"].astype(str)
df.loc[df.sample(frac=0.1).index,"department"]=df["department"].str.lower()


In [101]:
df.head()

student_id  age  marks department  Age  Marks  Department
0         101   18     92       AIML  NaN    NaN         NaN
1         102   21     56        CSE  NaN    NaN         NaN
2         103   22     65        CSE  NaN    NaN         NaN
3         104   20     46       AIML  NaN    NaN         NaN
4         105   18     80       AIML  NaN    NaN         NaN

In [102]:
df.tail()

student_id  age  marks department  Age  Marks  Department
995        1096   21     48       AIML  NaN    NaN         NaN
996        1097   21     76        CSE  NaN    NaN         NaN
997        1098   20     42       AIML  NaN    NaN         NaN
998        1099   21     62         ar  NaN    NaN         NaN
999        1100   23     54         me  NaN    NaN         NaN

In [108]:
df

student_id  age  marks department  Age  Marks  Department
0           101   18     92       AIML  NaN    NaN         NaN
1           102   21     56        cse  NaN    NaN         NaN
2           103   22     65        CSE  NaN    NaN         NaN
3           104   20     46       AIML  NaN    NaN         NaN
4           105   18     80       aiml  NaN    NaN         NaN
..          ...  ...    ...        ...  ...    ...         ...
995        1096   21     48       AIML  NaN    NaN         NaN
996        1097   21     76        CSE  NaN    NaN         NaN
997        1098   20     42       AIML  NaN    NaN         NaN
998        1099   21     62         ar  NaN    NaN         NaN
999        1100   23     54         me  NaN    NaN         NaN

[1000 rows x 7 columns]

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   student_id  1000 non-null   int64  
 1   age         1000 non-null   int32  
 2   marks       1000 non-null   int32  
 3   department  1000 non-null   object 
 4   Age         10 non-null     float64
 5   Marks       8 non-null      float64
 6   Department  0 non-null      float64
dtypes: float64(3), int32(2), int64(1), object(1)
memory usage: 47.0+ KB


In [110]:
df.isnull().sum()

student_id       0
age              0
marks            0
department       0
Age            990
Marks          992
Department    1000
dtype: int64

In [111]:
df.shape

(1000, 7)

In [112]:
df.columns

Index(['student_id', 'age', 'marks', 'department', 'Age', 'Marks',
       'Department'],
      dtype='object')

In [113]:
df.sample(10)

student_id  age  marks  department  Age  Marks  Department
645         746   22     72          ar  NaN    NaN         NaN
833         934   21     52          ME  NaN    NaN         NaN
78          179   20     54         CSE  NaN    NaN         NaN
773         874   18     40        aiml  NaN    NaN         NaN
649         750   21     92  automation  NaN    NaN         NaN
941        1042   22     55        AIML  NaN    NaN         NaN
606         707   20     45         CSE  NaN    NaN         NaN
768         869   23     66  automation  NaN    NaN         NaN
997        1098   20     42        AIML  NaN    NaN         NaN
615         716   22     66  automation  NaN    NaN         NaN

In [114]:
df.isnull().sum()

student_id       0
age              0
marks            0
department       0
Age            990
Marks          992
Department    1000
dtype: int64

In [117]:
df.isnull().mean()*100

student_id      0.0
age             0.0
marks           0.0
department      0.0
Age            99.0
Marks          99.2
Department    100.0
dtype: float64

In [118]:
df.isnull().any(axis=1)


0      True
1      True
2      True
3      True
4      True
       ... 
995    True
996    True
997    True
998    True
999    True
Length: 1000, dtype: bool

In [119]:
df[df.isnull().any(axis=1)].count()

student_id    1000
age           1000
marks         1000
department    1000
Age             10
Marks            8
Department       0
dtype: int64

In [120]:
df.duplicate().sum()

AttributeError: 'DataFrame' object has no attribute 'duplicate'

In [121]:
df.duplicated().sum()

np.int64(0)

In [123]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

np.int64(0)