In [ ]:
### welcome to numpy tutorial 

In [1]:
#with the import we can import any libraray in the python
import numpy as np

In [2]:
myarr=np.array([3,6,32,7])
print(myarr)

[ 3  6 32  7]


In [ ]:
myarr[1]

In [ ]:
myarr.shape

In [ ]:
myarr=np.array([[3,6,32,7]])
print(myarr)
myarr.shape
myarr[0,1]

In [ ]:
myarr.dtype

# Array creation : Conversion from other python structures

In [ ]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
print(listarray)

In [ ]:
listarray.dtype

In [ ]:
listarray.shape

In [ ]:
listarray.size

In [ ]:
zeros=np.zeros((2,5))
print(zeros)
print(zeros.dtype)

In [ ]:
rng=np.arange(15)
print(rng)

In [ ]:
lspace=np.linspace(1,5,12)
print(lspace)

In [ ]:
emp=np.empty((4,6))
print(emp)# provide the random numbers:

In [ ]:
emp_like = np.empty_like(lspace)
print(emp_like)

In [ ]:
ide=np.identity(4)

In [ ]:
print(ide)

In [ ]:
ide.shape

In [ ]:
arr=np.arange(98)

In [ ]:
print(arr,arr.dtype,arr.shape,arr.size)

In [ ]:
arr.reshape(2,49)

In [ ]:
arr

In [ ]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
print(ar)

In [ ]:
ar.sum(axis=0)

In [ ]:
ar.sum(axis=1)

In [ ]:
ar.T

In [ ]:
#max is provide the index of maximum element
one=np.array([1,3.47,63,2])
print(one.argmax())
              

In [ ]:
one.argmax()

In [ ]:
print(one.argsort())

In [ ]:
ar.argsort()

In [ ]:
 ar.sum()

In [ ]:
ar.max()

In [ ]:
ar.max()

In [ ]:
ar.min()

In [ ]:
arr.max()

In [ ]:
ar

In [ ]:
print(np.where(ar>5))
print(type(ar))

In [ ]:
import numpy as np


In [ ]:
myarr=np.array([1,2,3,4,5,6,7])
print(myarr)

In [ ]:
myarr.sum()

In [ ]:
myarr.max()

In [ ]:
myarr.min()

In [ ]:
print(myarr)

In [ ]:
print(type(myarr))

In [ ]:
myarr.dtype

In [ ]:
yarr=np.array([1,5,6,7])
print(yarr)

In [ ]:
print(np.__version__)

In [ ]:
#creating arrays

In [ ]:
list1=[1,2,3]
print(list1)

In [ ]:
arr_list1=np.array(list1)

In [ ]:
print(arr_list1)

In [ ]:
print(type(arr_list1))

In [ ]:
list1=[1,2,3]
list2=[4,5,6]
arr_list_2=np.array([list1,list2])
print(arr_list_2)

In [ ]:
print(type(arr_list_2))

In [ ]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
print([list1,list2,list3])
arr_list_3=np.array([[list1,list2,list3]])
print(arr_list_3)

In [ ]:
print(type(arr_list_3))

In [ ]:
print(arr_list_3.ndim)

In [ ]:
# 2.numpy array attributes

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)#two dimenstion array is 

In [ ]:
print("shape is",arr1.shape)
print("size is ",arr1.size)
print("dtypw is ",arr1.dtype)
print("n_dim is ",arr1.ndim)



In [ ]:
#3 array initialization methods

In [ ]:
#zero array is 
zero_arr=np.zeros((2,3))
print(zero_arr)

In [ ]:
one_arr=np.ones((3,2))
print(one_arr)

In [ ]:
full_arr=np.full((3,2),7)
print(full_arr)

In [ ]:
#indentity methods
id_arr=np.eye(3)
print(id_arr)

In [ ]:
#empty array
print(np.empty(2))

In [ ]:
#evenly space array
print(np.arange(1,8,2))

In [ ]:
#specific number of eqaully (spaced) value between a range is 
print(np.linspace(1,10,4))


In [ ]:
#randam value array is genrate is
r_arr=np.random.rand(3,2)#it is genrate the float value is 
print(r_arr)

In [ ]:
r_arr=np.random.randint(1,10,(3,3))
print(r_arr)

In [ ]:
# 4array indexing and slicing of the array is 

In [ ]:
a=np.array([1,3,5,7,9])
print(a)

In [ ]:
print(a[0])

In [ ]:
print(a[-1])

In [ ]:
a=np.array([1,3,5,7,9])
print(a)

In [ ]:
#slicing teh array 
#array[start:stop:step]
#stop index ,that is not included in output
print(a[0:3])


In [ ]:
print (a[0::3])#first 3 element

In [ ]:
print(a[-1])#last 3 element 

In [ ]:
print(a[-3])#last 3 elemets

In [ ]:
print(a[0:4:2])

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

In [ ]:
print(arr2[0])

In [ ]:
print(arr2[1][0])

In [ ]:
print(arr2[1::])

In [ ]:
print(arr2[:1])

In [ ]:
print(arr2[:])

In [ ]:
print(arr2[:,0])
#2d:[rows,colums]
#3d:[layes/height,rows,columns]

In [ ]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)

In [ ]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

In [ ]:
print(arr3[0][2])
print(arr3[1][2])
print(arr3[2][2])

In [ ]:
print(arr3[::,2])#2nd col value is 
print(arr3[:,2])#2nd col value is :

In [ ]:
# 5 array reshaping and flattening

In [ ]:
arr1=np.array([1,2,3,4,5,6])
print(arr1)

In [ ]:
#reshape the element of the array is 
reshape=arr1.reshape((6,1)) #shape before the reshape is (1 row and 6 columns) dimension 1
print(reshape)#shape after the reshape is (6 rows and 1 column) dimensionn=2

In [ ]:
reshape2=arr1.reshape((3,2))
print(reshape2)

In [ ]:
print(reshape2.flatten())

In [ ]:
#array stacking and slitting
# there ara the two type ift tyhe stacking 
#first is vertical and horigontal
a=np.array([1,2,3])
print(a)
b=np.array([4,5,6])
print(b)

In [ ]:
print(np.vstack(a))#vertical stacking-row wise

In [ ]:
print(np.hstack(a))#horizontal stacking-column wise

In [ ]:
print(np.vstack((a,b)))#vertical stacking-row wise of a and b is 

In [ ]:
print(np.hstack((a,b)))#horizontal staking column wise of a and b is

In [ ]:
#7 mathematical operations on array is 
a=np.array([10,20,40,50])
print(a)

In [ ]:
print(a+10)#addition 
print(a-10)#subtraction
print(a*2)#multiplication
print(a/30)#division

In [ ]:
print(np.square(a))
print(np.sqrt(a))

In [5]:
import numpy as np

In [11]:
np.concatenate(([1,2],[3,4]))

array([1, 2, 3, 4])

In [13]:
arr=("vishal","nishant","abhi","ram")
print(arr)

('vishal', 'nishant', 'abhi', 'ram')


In [15]:
arr2=np.array(arr)
print(arr2)

['vishal' 'nishant' 'abhi' 'ram']


In [19]:
arr2[0]="ban"

In [21]:
print(arr2)

['ban' 'nishant' 'abhi' 'ram']


In [23]:
np.split(arr2,2)

[array(['ban', 'nishant'], dtype='<U7'), array(['abhi', 'ram'], dtype='<U7')]

In [25]:
#practice question of the numpy library in the python language 

In [27]:
list1=[1,2,3,4,5,6]
print(list1)
arr1=np.array(list1)
print(arr1)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [ ]:
arr2=np.zeros(3)
print(arr2)
arr3=np.ones(3)
print(arr3)

In [29]:
np.shape(arr1)


(6,)

In [31]:
np.size(arr1)

6

In [33]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [35]:
arr4=np.array([[1,2],[3,4],[5,6]])
print(arr4)

[[1 2]
 [3 4]
 [5 6]]


In [37]:
np.reshape(arr4,[2,3])

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr5= np.array([1,2,3,4,np.nan,5,6 ])
print(arr5)

[ 1.  2.  3.  4. nan  5.  6.]


In [63]:
np.isnan(arr5)

array([False, False, False, False,  True, False, False])

In [85]:
arr5[np.isnan(arr5)] = np.nanmean(arr5)

In [47]:
print(arr5)

[1.  2.  3.  4.  3.5 5.  6. ]


In [57]:
arr6=np.array([[1,2,np.nan],[4,5,6]])
print(arr6)

[[ 1.  2. nan]
 [ 4.  5.  6.]]


In [65]:
np.isnan(arr6)

array([[False, False,  True],
       [False, False, False]])

In [69]:
arr = np.array([-1, 2, -3, 4])
arr[arr < 0] = 0
print(arr)

[0 2 0 4]


In [73]:
arr3=np.arange(10,50,1)
print(arr3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [79]:
arr4=np.array([1,2,3,4,1,1,1,2,2,2])
print(arr4)
np.unique(arr4)

[1 2 3 4 1 1 1 2 2 2]


array([1, 2, 3, 4])

In [97]:
arr = np.array([10, 12, 11, 100]) 
z = (arr - np.mean(arr)) / np.std(arr)
print(arr,z)

[ 10  12  11 100] [-0.60319707 -0.55130915 -0.57725311  1.73175933]


In [99]:
arr=np.arange(0,1)

In [105]:
arr = np.array([10, 12, 11, 100]) 
arrmean=(arr-np.mean(arr))
arrstd=np.std(arr)
print(arrmean+arrstd)

[ 15.294617  17.294617  16.294617 105.294617]


In [129]:
arr6=("5.0","5.4","5.4")
gy = arr.astype(float)
np.array(gy)

array([ 10.,  12.,  11., 100.])

In [150]:
arr = np.array([1, 999, 3],dtype=float)
arr[arr == 999]
print(arr) 

[  1. 999.   3.]


In [152]:
arr = np.array([1, np.nan, 3, 4, 5])
arr[np.isnan(arr)] = np.nanmedian(arr)
print(arr) 

[1.  3.5 3.  4.  5. ]


In [3]:
arr = np.array([1.2345, 2.6789])
print(np.round(arr, 2))

[1.23 2.68]


In [4]:
#How can you detect and remove infinite values (inf, -inf) from a NumPy array?
arr=np.array([1,2,np.inf,-np.inf])
print(arr)
inf_indices=np.isinf(arr)
print(inf_indices)
arr[inf_indices]=0
print(arr)

[  1.   2.  inf -inf]
[False False  True  True]
[1. 2. 0. 0.]


In [5]:
#How do you sort a NumPy array while keeping track of original indices
arr=np.array([3,1,4,2])
print(arr)
sorted_indices=np.argsort(arr)
print(sorted_indices)
sorted_arr=arr[sorted_indices]
print(sorted_arr)

[3 1 4 2]
[1 3 0 2]
[1 2 3 4]


In [6]:
#How do you check if an array contains any null or invalid values?
arr=np.array([1,2,np.nan,4])
print(np.isnan(arr).any())

True


In [ ]:
#How can boolean masking be used to clean unwanted values from a NumPy array?
arr=np.array([1,2,-99,4,5,-99])
print(arr)
mask=arr!=-99
print(mask)