### welcome to numpy tutorial 

In [3]:
#with the import we can import any libraray in the python
import numpy as np

In [10]:
myarr=np.array([3,6,32,7])
print(myarr)

[ 3  6 32  7]


In [16]:
myarr[1]

6

In [12]:
myarr.shape

(4,)

In [22]:
myarr=np.array([[3,6,32,7]])
print(myarr)
myarr.shape
myarr[0,1]

[[ 3  6 32  7]]


6

In [24]:
myarr.dtype

dtype('int32')

# Array creation : Conversion from other python structures

In [38]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
print(listarray)

[[1 2 3]
 [5 8 5]
 [0 3 1]]


In [40]:
listarray.dtype

dtype('int32')

In [42]:
listarray.shape

(3, 3)

In [48]:
listarray.size

9

In [54]:
zeros=np.zeros((2,5))
print(zeros)
print(zeros.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64


In [56]:
rng=np.arange(15)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [60]:
lspace=np.linspace(1,5,12)
print(lspace)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [62]:
emp=np.empty((4,6))
print(emp)# provide the random numbers:

[[6.23042070e-307 1.86918699e-306 1.69121096e-306 6.23058707e-307
  8.45593934e-307 7.56593017e-307]
 [1.11261027e-306 1.11261502e-306 1.42410839e-306 7.56597770e-307
  6.23059726e-307 8.90104239e-307]
 [6.89804133e-307 1.69118923e-306 1.33511562e-306 6.23061084e-307
  9.34598926e-307 1.69121096e-306]
 [1.05700515e-307 2.04712906e-306 7.56589622e-307 1.11258277e-307
  8.90111708e-307 2.22522597e-306]]


In [74]:
emp_like = np.empty_like(lspace)
print(emp_like)

[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]


In [84]:
ide=np.identity(4)

In [86]:
print(ide)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [88]:
ide.shape

(4, 4)

In [125]:
arr=np.arange(98)

In [129]:
print(arr,arr.dtype,arr.shape,arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97] int32 (98,) 98


In [137]:
arr.reshape(2,49)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48],
       [49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
        81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
        97]])

In [141]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97])

In [145]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
print(ar)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [157]:
ar.sum(axis=0)

array([12,  8,  9])

In [149]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [155]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [159]:
#max is provide the index of maximum element
one=np.array([1,3.47,63,2])
print(one.argmax())
              

2


In [167]:
one.argmax()

2

In [165]:
print(one.argsort())

[0 3 1 2]


In [170]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [172]:
 ar.sum()

29

In [174]:
ar.max()

7

In [176]:
ar.max()

7

In [178]:
ar.min()

0

In [180]:
arr.max()

97

In [182]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [190]:
print(np.where(ar>5))
print(type(ar))

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))
<class 'numpy.ndarray'>


In [4]:
import numpy as np


In [15]:
myarr=np.array([1,2,3,4,5,6,7])
print(myarr)

[1 2 3 4 5 6 7]


In [17]:
myarr.sum()

28

In [19]:
myarr.max()

7

In [21]:
myarr.min()

1

In [29]:
print(myarr)

[1 2 3 4 5 6 7]


In [31]:
print(type(myarr))

<class 'numpy.ndarray'>


In [33]:
myarr.dtype

dtype('int32')

In [39]:
yarr=np.array([1,5,6,7])
print(yarr)

[1 5 6 7]


In [6]:
print(np.__version__)

1.26.4


In [8]:
#creating arrays

In [10]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [12]:
arr_list1=np.array(list1)

In [14]:
print(arr_list1)

[1 2 3]


In [16]:
print(type(arr_list1))

<class 'numpy.ndarray'>


In [18]:
list1=[1,2,3]
list2=[4,5,6]
arr_list_2=np.array([list1,list2])
print(arr_list_2)

[[1 2 3]
 [4 5 6]]


In [20]:
print(type(arr_list_2))

<class 'numpy.ndarray'>


In [64]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
print([list1,list2,list3])
arr_list_3=np.array([[list1,list2,list3]])
print(arr_list_3)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [35]:
print(type(arr_list_3))

<class 'numpy.ndarray'>


In [66]:
print(arr_list_3.ndim)

3


In [68]:
# 2.numpy array attributes

In [70]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)#two dimenstion array is 

[[1 2 3]
 [4 5 6]]


In [74]:
print("shape is",arr1.shape)
print("size is ",arr1.size)
print("dtypw is ",arr1.dtype)
print("n_dim is ",arr1.ndim)



shape is (2, 3)
size is  6
dtypw is  int32
n_dim is  2


In [76]:
#3 array initialization methods

In [78]:
#zero array is 
zero_arr=np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [84]:
one_arr=np.ones((3,2))
print(one_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [86]:
full_arr=np.full((3,2),7)
print(full_arr)

[[7 7]
 [7 7]
 [7 7]]


In [88]:
#indentity methods
id_arr=np.eye(3)
print(id_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [90]:
#empty array
print(np.empty(2))

[4.74795561e-265 3.27274059e+224]


In [100]:
#evenly space array
print(np.arange(1,8,2))

[1 3 5 7]


In [108]:
#specific number of eqaully (spaced) value between a range is 
print(np.linspace(1,10,4))


[ 1.  4.  7. 10.]


In [110]:
#randam value array is genrate is
r_arr=np.random.rand(3,2)#it is genrate the float value is 
print(r_arr)

[[0.0614508  0.46942993]
 [0.33617997 0.84883176]
 [0.95546545 0.56000161]]


In [112]:
r_arr=np.random.randint(1,10,(3,3))
print(r_arr)

[[7 2 3]
 [5 8 2]
 [9 4 2]]


In [114]:
# 4array indexing and slicing of the array is 

In [116]:
a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [118]:
print(a[0])

1


In [120]:
print(a[-1])

9


In [122]:
a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [126]:
#slicing teh array 
#array[start:stop:step]
#stop index ,that is not included in output
print(a[0:3])


[1 3 5]


In [140]:
print (a[0::3])#first 3 element

[1 7]


In [132]:
print(a[-1])#last 3 element 

9


In [136]:
print(a[-3])#last 3 elemets

5


In [138]:
print(a[0:4:2])

[1 5]


In [142]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [144]:
print(arr2[0])

[1 2 3]


In [156]:
print(arr2[1][0])

4


In [160]:
print(arr2[1::])

[[4 5 6]]


In [164]:
print(arr2[:1])

[[1 2 3]]


In [168]:
print(arr2[:])

[[1 2 3]
 [4 5 6]]


In [170]:
print(arr2[:,0])
#2d:[rows,colums]
#3d:[layes/height,rows,columns]

[1 4]


In [172]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [174]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [180]:
print(arr3[0][2])
print(arr3[1][2])
print(arr3[2][2])

3
6
9


In [182]:
print(arr3[::,2])#2nd col value is 
print(arr3[:,2])#2nd col value is :

[3 6 9]
[3 6 9]


In [186]:
# 5 array reshaping and flattening

In [216]:
arr1=np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [220]:
#reshape the element of the array is 
reshape=arr1.reshape((6,1)) #shape before the reshape is (1 row and 6 columns) dimension 1
print(reshape)#shape after the reshape is (6 rows and 1 column) dimensionn=2

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [228]:
reshape2=arr1.reshape((3,2))
print(reshape2)

[[1 2]
 [3 4]
 [5 6]]


In [232]:
print(reshape2.flatten())

[1 2 3 4 5 6]


In [234]:
#array stacking and slitting
# there ara the two type ift tyhe stacking 
#first is vertical and horigontal
a=np.array([1,2,3])
print(a)
b=np.array([4,5,6])
print(b)

[1 2 3]
[4 5 6]


In [236]:
print(np.vstack(a))#vertical stacking-row wise

[[1]
 [2]
 [3]]


In [238]:
print(np.hstack(a))#horizontal stacking-column wise

[1 2 3]


In [244]:
print(np.vstack((a,b)))#vertical stacking-row wise of a and b is 

[[1 2 3]
 [4 5 6]]


In [246]:
print(np.hstack((a,b)))#horizontal staking column wise of a and b is

[1 2 3 4 5 6]


In [248]:
#7 mathematical operations on array is 
a=np.array([10,20,40,50])
print(a)

[10 20 40 50]


In [250]:
print(a+10)#addition 
print(a-10)#subtraction
print(a*2)#multiplication
print(a/30)#division

[20 30 50 60]
[ 0 10 30 40]
[ 20  40  80 100]
[0.33333333 0.66666667 1.33333333 1.66666667]


In [252]:
print(np.square(a))
print(np.sqrt(a))

[ 100  400 1600 2500]
[3.16227766 4.47213595 6.32455532 7.07106781]
