In [3]:
import cv2

In [4]:
import cv2
import numpy as np
import sys

In [5]:
img = cv2.imread("image.jpeg")
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:

print (img[:,:,2])

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [7]:
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Cannot open camera")
else:
    while True:
        ret, frame = cap.read()
        if not ret:
            print("Can't receive frame (stream end?). Exiting ...")
            break
        cv2.imshow('Webcam', frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
        if cv2.getWindowProperty('Webcam', cv2.WND_PROP_VISIBLE) < 1:
            break
    cap.release()
    cv2.destroyAllWindows()


In [8]:
print (img.shape)

(600, 800, 3)


In [9]:
print(img[0,400])

[255 255 255]
