In [3]:
import cv2

In [4]:
import cv2
import numpy as np
import sys

In [5]:
img = cv2.imread("image.jpeg")
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:

print (img[:,:,2])

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [7]:
cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("Cannot open camera")
else:
    while True:
        ret, frame = cap.read()
        if not ret:
            print("Can't receive frame (stream end?). Exiting ...")
            break
        cv2.imshow('Webcam', frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
        if cv2.getWindowProperty('Webcam', cv2.WND_PROP_VISIBLE) < 1:
            break
    cap.release()
    cv2.destroyAllWindows()


In [8]:
print (img.shape)

(600, 800, 3)


In [9]:
print(img[0,400])

[255 255 255]


In [3]:
import cv2          #Import the OpenCV pip install opencv
import numpy as np   #Import the Numpy library
import sys
print ("You have successfully installed OpenCV version")

You have successfully installed OpenCV version


In [5]:
img = cv2.imread("[Dataset] Module 20 images/image001.png") #Load
the image file into memory
cv2.imshow("Image", img) #Display that image
cv2.waitKey(0) #Cleanup after any key is
pressed
cv2.destroyAllWindows()
libpng warning: iCCP: known incorrect sRGB profile
2025-12-24 10:13:23.664 python[2046:24380] +[IMKClient subclass]:
chose IMKClient_Modern
2025-12-24 10:13:23.664 python[2046:2438]

SyntaxError: invalid syntax (Temp/ipykernel_27216/4008848309.py, line 2)